spring.application.name=expenses-backend

# ==============================================================================
# Server Configuration
# ==============================================================================
server.port=${SERVER_PORT:8084}

# ==============================================================================
# Database Configuration (PostgreSQL)
# ==============================================================================
spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${JPA_DDL:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.open-in-view=false
# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ==============================================================================
# Security Configuration (JWT)
# ==============================================================================
application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=86400000

# ==============================================================================
# Email Configuration (SMTP)
# ==============================================================================
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}

spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=30000
spring.mail.properties.mail.smtp.timeout=30000
spring.mail.properties.mail.smtp.writetimeout=30000

# ==============================================================================
# Infrastructure & Logging
# ==============================================================================
logging.level.root=${LOG_LEVEL_ROOT:WARN}
logging.level.com.expense.tracker=${LOG_LEVEL_APP:INFO}
logging.level.com.expense.tracker.service.SmsService=DEBUG

# Connection Pool
spring.datasource.hikari.pool-name=ExpensioHikariCP
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=2

# Enable all actuator endpoints
management.endpoints.web.exposure.include=*

# Health endpoint
management.endpoint.health.show-details=always

# Prometheus endpoint
management.endpoint.prometheus.enabled=true

# Enable Prometheus export
management.prometheus.metrics.export.enabled=true
